version: "2"

services:
  backend:
    build: backend
    image: ${REGISTRY_SLASH}backend${COLON_TAG}
    ports:
    - "4000:80"

  frontend:
    build: frontend
    image: ${REGISTRY_SLASH}frontend${COLON_TAG}
    ports:
    - "3000:80"
